name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [expo, react-native]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: |
            ${{ matrix.package }}/package-lock.json

      # Add a debug step to check files
      - name: Debug - List Files
        run: |
          ls -la ${{ matrix.package }}/package-lock.json
          echo "Current directory: $(pwd)"
          echo "Package directory contents:"
          ls -la ${{ matrix.package }}/

      - name: Install dependencies
        working-directory: ./${{ matrix.package }}
        run: npm ci

      - name: Build
        working-directory: ./${{ matrix.package }}
        run: npm run build

      # For react-native package only
      - name: Run tests
        if: matrix.package == 'react-native'
        working-directory: ./react-native
        run: npm test
        continue-on-error: true # Make tests optional for now

      # Type checking - only for react-native
      - name: Type check
        if: matrix.package == 'react-native'
        working-directory: ./${{ matrix.package }}
        run: npm run typescript

      # Optional: Lint check - only for react-native
      - name: Lint
        if: matrix.package == 'react-native'
        working-directory: ./react-native
        run: npm run lint
