name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # React Native CLI Package
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
          cache-dependency-path: "react-native/package-lock.json"

      - name: Install RN CLI dependencies
        run: |
          cd react-native
          npm install --force
          npm run build

      # Expo Package
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
          cache-dependency-path: "expo/package-lock.json"

      - name: Install Expo dependencies
        run: |
          cd expo
          npm install --legacy-peer-deps
          npm run build
